package com.relationalcloud.tsqlparser.visitors.recursive;

public enum ASTContext {
	NONE,
	PROJECTIONS, // SELECT (...) FROM ...
	FROM, // SELECT ... FROM (...) WHERE ...
	WHERE, // SELECT ... FROM ... WHERE (...) ...
	GROUP_BY, // SELECT ... FROM ... WHERE ... GROUP BY (...) ...
	ORDER_BY, // SELECT ... FROM ... WHERE ... GROUP BY ... ORDER BY (...)
}
